# -*- coding: utf-8 -*-
"""Sinclair_Hansen_Kanerva.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152zL7Qo0SP_fdXFHlhCXGawCpFF21RCt
"""

import random
import numpy as np
import math
import collections
import re


letter_dict = {}
vec_names = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v',
                          'w','x','y','z', ' ']
for i, l in enumerate(vec_names):
      letter_dict[l] = 2*np.random.randint(0, 2, size=(10000))-np.ones((10000))

class Word_as_vec:
    def __init__(self, lines, letter_dict):
        self.lines = lines
        self.trigrams = []
        self.prof_vec = np.zeros(())
        self.l2i = {}
        self.i2l = {}
        self.vector_size = 10000

        self.letterdict = letter_dict
        self.worddict = collections.defaultdict(lambda: None)

        self.letter_vectors_as_matrix = np.array(list(self.letterdict.values()))
        return

    def cossim(self,x,y):
        return  np.dot(x,np.transpose(y))/(math.sqrt(np.dot(x,np.transpose(x)))*math.sqrt(np.dot(y,np.transpose(y))))

    def pm(self,x,offset):
        return np.concatenate((x[offset:], x[0:offset]))

    def ipm(self,x):
        return np.concatenate((x[-1:], x[:-1]))

    def most_similar(self,x):
        closest_letter = self.i2l[np.argmax(np.matmul(self.letter_vectors_as_matrix, x))]
        cosine_similarity = self.cossim(x, self.letterdict[closest_letter])
        return self.letterdict[closest_letter], closest_letter, cosine_similarity
        #  vector                                  letter          cosine

    def create_vector_for_trigrams(self):
        vec = np.zeros((self.vector_size))
        for trigram in self.trigrams:
          vec+=self.letterdict[trigram[0]] *self.pm(self.letterdict[trigram[1]], 1) *self.pm(self.letterdict[trigram[2]], 2)
        self.prof_vec = vec

    def unbind_vec(self, vec):
        residue = vec
        cos = -1
        for i in range(800):
            prev_cos = cos
            best_vec, closest, cos = self.most_similar(residue)
            if prev_cos / cos > 3:
                break
            print(closest, end='')
            if i > 0 and i % 120 == 0:
                print()
            #print(closest, round(cos,3))
            if cos == 1:
                break
            residue = self.ipm(np.subtract(residue, best_vec))

    def get_trigrams_from_lines(self):
      for line in self.lines:
        line_len = len(line)
        last_index = 3
        while last_index <= line_len:
          words = line[last_index-3: last_index]
          last_index += 1
          self.trigrams.append(words)

def clean(line):
    line = line.lower()

    if line.startswith('['):
        return None
    line = line.rstrip('\n')

    line = line.replace('-', ' ')
    line = re.sub(r'[^a-z\s]', '', line)

    return line

elton = []
with open('EltonJohn.txt') as f:
    for line in f:
      line = clean(line)
      if line is not None:
        elton.append(line)
paul = []
with open('PaulMcCartney.txt') as f:
    for line in f:
      line = clean(line)
      if line is not None:
        paul.append(line)
taylor = []
with open('TaylorSwift.txt') as f:
    for line in f:
      line = clean(line)
      if line is not None:
        taylor.append(line)
chaucer = []
with open('chaucer.txt') as f:
    for line in f:
      line = clean(line)
      if line is not None:
        chaucer.append(line)
coleridge = []
with open('coleridge.txt') as f:
    for line in f:
      line = clean(line)
      if line is not None:
        coleridge.append(line)
mariner = []
with open('mariner.txt') as f:
    for line in f:
      line = clean(line)
      if line is not None:
        mariner.append(line)
shake = []
with open('shakespeares_sonnets.txt') as f:
    for line in f:
      line = clean(line)
      if line is not None:
        shake.append(line)
waste = []
with open('wasteland.txt') as f:
    for line in f:
      line = clean(line)
      if line is not None:
        waste.append(line)

elton_obj = Word_as_vec(elton, letter_dict)
paul_obj = Word_as_vec(paul, letter_dict)
taylor_obj = Word_as_vec(taylor, letter_dict)
chaucer_obj = Word_as_vec(chaucer, letter_dict)
coler_obj = Word_as_vec(coleridge, letter_dict)
mariner_obj = Word_as_vec(mariner, letter_dict)
shake_obj = Word_as_vec(shake, letter_dict)
waste_obj = Word_as_vec(waste, letter_dict)

all_list = [elton_obj,paul_obj,taylor_obj,chaucer_obj,coler_obj,mariner_obj,shake_obj,waste_obj]
for obj in all_list:
    obj.get_trigrams_from_lines()
    obj.create_vector_for_trigrams()

all_objs = {}
all_objs[elton_obj] = 'EltonJohn.txt'
all_objs[paul_obj] = 'PaulMcCartney.txt'
all_objs[taylor_obj] = 'TaylorSwift.txt'
all_objs[chaucer_obj] = 'chaucer.txt'
all_objs[coler_obj] = 'coleridge.txt'
all_objs[mariner_obj] = 'mariner.txt'
all_objs[shake_obj] = 'shakespeares_sonnets.txt'
all_objs[waste_obj] = 'wasteland.txt'

for obj1, file1 in all_objs.items():
  for obj2 in all_list:
    if obj1 == obj2:
      continue
    similarity = obj1.cossim(obj1.prof_vec, obj2.prof_vec)
    print(file1 + " " + all_objs[obj2] + " " + format(similarity,".4f"))

print('''
Part B:
__________________

Elton John
----------
Most Similar: Paul McCartney 0.9215
Least Similar: Chaucer 0.7539

It makes sense that Paul McCartney is the most similar. Elton is the closest
in time to Paul and their writing should be similar since they are writing popular music in a similar timeframe.
Chaucer is in a completely different time period and has a completely
different writing purpose/style so it makes sense that Elton + Chaucer are very different.


Paul McCartney
--------------
Most Similar: Taylor Swift 0.9337
Least Similar: Chaucer 0.7734

I guess this is mildly surprising since I would expect Elton to be closer. Regardless,
it does make sense that another modern musician is one of the closest since the writing
is going to have a similar style.

Similar to Elton, the reason why Chaucer is so distant is likely due to his writing
coming from a completely different time period, having a different style, and serving
a different purpose.

Taylor Swift
------------
Most Similar: Paul McCartney 0.9337
Least Similar: Chaucer 0.7082

Again it makes sense that these are the most similar, especially since we already
found that Paul was already most similar to Taylor. All the musicians have Chaucer
as the furthest which makes sense given time period and writing style.

Chaucer
-------
Most Similar: Coleridge 0.8657
Least Similar: Taylor Swift 0.7082

It makes sense that Coleridge was the most similar because they are both old english poets
which means their writing will have more similarity in style when compared to the modern
musicians.

Taylor being the least similar is due to them having different writing styles,
coming from different time periods, and Chaucer likely isn't talking about his break up
with Harry Styles in his writing.

Coleridge
---------
Most Similar: Mariner 0.9334
Least Similar: Taylor Swift 0.7431

Mariner is written by Coleridge so that's why they are quite similar.
Taylor Swift likely doesn't match the writing style of Coleridge.


Mariner
--------
Most Similar: Wasteland 0.9260
Least Similar: Taylor Swift 0.7330

I would think that Mariner and Coleridge would be similar again, but regardless
it does make sense that another poem is higher up. There are clear trends for the
older writing samples having Taylor Swift being the least similar.
It makes sense due to their different periods and writing styles.


Shakespeare
------------
Most Similar: Coleridge 0.8650
Least Similar: Taylor Swift 0.7644

Similar to the previous sets of poets, these make sense given the similarities
that Shakespeare and Coleridge would have. Taylor is going to have simplified
and modern writing which would make her more distant to Shakespeare.

Wasteland
---------
Most Similar: Mariner 0.9260
Least Similar: Taylor Swift 0.8082

It does make sense that Wasteland and Mariner are the most similar. Out of the poets,
Mariner is the closest in time period which means they would likely be closest in style when
compared to Shakespeare and Chaucer.
Taylor Swift is no longer surprising.

______________________
Largest Difference Overall:

Taylor Swift and Chaucer: 0.7082

It does not surprise me that Taylor shows up here. It also makes sense that Chaucer does
as these two are the furthest in time period. Chaucer has old-english in his writing and
Taylors lyrics are going to be more modern and simplistic. I just read some Chaucer and yes,
they are completely different.

''')