# -*- coding: utf-8 -*-
"""Sinclair_Hansen_German.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19tsWTfKqQKak_bcBhhQfrvKnut8E9b1b
"""

import torch.nn as nn
import torch
import torch.optim as optim

det_indices = {}
dets = ['der', 'die', 'das', 'dem', 'des', 'den']
gen_indices = {}
genders = ['M', 'F', 'N']
case_indices = {}
cases = ['N', 'A', 'D', 'G']
num = ['SNG', 'PL']
num_indices = {}

for i, d in enumerate(dets):
  det_indices[d] = torch.tensor(i)
for i, g in enumerate(genders):
  gen_indices[g] = torch.tensor(i)
for i, c in enumerate(cases):
  case_indices[c] = torch.tensor(i)
for i, n in enumerate(num):
  num_indices[n] = torch.tensor(i)

lr = 0.03

class PredDet(nn.Module):
  def __init__(self):
    super(PredDet, self).__init__()
    self.layer = nn.Linear(9, 6)
    self.num_embedding = nn.Embedding(2, 2)
    self.gen_embedding = nn.Embedding(3, 3)
    self.case_embedding = nn.Embedding(4, 4)

  def forward(self, in_vec):
    return torch.unsqueeze(self.layer(in_vec), 0)

net = PredDet()
criterion = nn.CrossEntropyLoss()
optimiser = torch.optim.Adam(net.parameters(), lr=lr)

num_epochs = 100

for epoch in range(num_epochs):
  all_correct = True
  epoch_loss = 0

  for n in num:
    for g in genders:
      for c in cases:
        num_emb = net.num_embedding(num_indices[n])
        gen_emb = net.gen_embedding(gen_indices[g])
        case_emb = net.case_embedding(case_indices[c])

        input_v = torch.cat((num_emb, gen_emb, case_emb), dim=0)

        if n == 'PL':
          if c == 'N':
            target = 'die'
          elif c == 'A':
            target = 'die'
          elif c == 'D':
            target = 'den'
          else:
            target = 'der'
        else:
          if g == 'N':
            if c == 'N':
              target = 'das'
            elif c == 'A':
              target = 'das'
            elif c == 'D':
              target = 'dem'
            else:
              target = 'des'
          elif g == 'M':
            if c == 'N':
              target = 'der'
            elif c == 'A':
              target = 'den'
            elif c == 'D':
              target = 'dem'
            else:
              target = 'des'
          else:
            if c == 'N' or c == 'A':
              target = 'die'
            else:
              target = 'der'

        target_v = torch.unsqueeze(det_indices[target], 0)
        target_v = target_v.long()

        pred = net(input_v)
        loss = criterion(pred, target_v)

        epoch_loss += loss.detach()

        loss.backward()
        optimiser.step()
        optimiser.zero_grad()

        with torch.no_grad():
          argmaxed = torch.argmax(pred, dim=1).item()
          print(n + " " + g + " " + c + " " + str(argmaxed) + " "+ str(target_v.item()))
          if argmaxed != target_v.item():
            all_correct = False

  print("Epoch Loss: " + str(epoch_loss))


  if all_correct:
    print("All predictions are correct after " + str(epoch + 1) + " iterations.")
    break

print("Trying Namreg: The model fails to guess all the articles correctly")







