# -*- coding: utf-8 -*-
"""Sinclair_Hansen_Trigrams.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quxdS2HJevIl90kgIBYMrIPpUIgvwtid
"""

import os
import re
import random


list_of_lines = []
with open('emma_nnl.txt', 'r') as f0:
    for line in f0.readlines():
        line = line.rstrip()
        list_of_lines.append(line)

class data:
  def __init__(self, file, num_words = 200):
    self.file = file
    self.num_words = num_words
    self.lines = []
    self.trigrams = []
    if os.path.isfile(self.file):
      list_of_lines = []
      with open(self.file, 'r', encoding='utf-8-sig') as f0:
          for line in f0.readlines():
              line = line.rstrip()
              if len(line) <= 1 or line.startswith('['):
                continue

              line = re.sub(r'\b(Mr|Mrs|Dr|St)\.', r'\1', line)
              line = re.sub(r'(?<=\S)([.,:;!?]|\u201D)|\u201C(?=\S)',lambda m: (' ' +
                            m.group(1)) if m.group(1) else '\u201C ',line)
              line = re.sub(r"\d+", "", line)
              line = re.sub(r"[_\u2018]", "", line)
              line = re.sub(r"(?<=\s)\u2019", "", line)
              line = re.sub(r"\u2012|--", lambda m: " " if m.group(0) == '\u2012' else " -- ", line)
              tokens = re.findall(r"\w+|[^\w\s]", line)
              if len(tokens) > 9:
                self.lines.append(tokens)

  def get_trigrams_from_lines(self):
    for line in self.lines:
      line_len = len(line)
      last_index = 3
      while last_index <= line_len:
        words = line[last_index-3: last_index]
        last_index += 1
        self.trigrams.append(words)
  def choose_random_starting_trigram(self):
    start = random.choice([t for t in self.trigrams if t[0][0].isupper()])
    return start


  def get_next_trigram(self, current_trigram, index_1 = 2, index_2 = 1):
    possible_tris = [t for t in self.trigrams if t[:index_1] == current_trigram[index_2:]]
    if len(possible_tris) > 0:
      next = random.choice(possible_tris)
      return next
    else:
      return None


  def generate_text(self):
    output = []
    self.get_trigrams_from_lines()
    current_trigram = self.choose_random_starting_trigram()
    output.append(current_trigram[0])
    output.append(current_trigram[1])
    output.append(current_trigram[2])
    list_of_grams = []
    count = 0
    while(count < self.num_words - 3):
      count += 1
      next = self.get_next_trigram(current_trigram)
      if(next == None):
        next = self.get_next_trigram(current_trigram, index_1=0, index_2=2)
      if(next == None):
        break
      output.append(next[2])
      current_trigram = next

    output_str = " ".join(output)
    print(output_str)



d = data("emma_nnl.txt", 200)
d.generate_text()

print("Longest coherent string: \"To that surmise, without our sighing out our souls over this charade.\"")


print("Discontinuity example: \"He would not it possible\"")

print("The words \"would not it\" are not natural in English. It would " +
      "be more likely for us to us \"would it not\"" +
      " as well as this \"not it possible \" does not make sense. Maybe use 'impossible' instead?")