# -*- coding: utf-8 -*-
"""SinclairHansen_Estonian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UrijBummD9mSfLbesqUW30WxKBnsIIB2
"""

import collections
from collections import defaultdict
import re
forms_dict= {}

with open("Estonian-1.txt", "r", encoding='utf-8') as f:
  for line in f:
    line = line.rstrip()
    if re.search("nom_sg", line):
      nom = re.sub(r".*nom_sg\t", "", line)
      current_lexeme = nom
      forms_dict[current_lexeme] = [nom]

    elif re.search("gen_sg", line):
      gen = re.sub(r".*gen_sg\t", "", line)
      forms_dict[current_lexeme].append(gen)

    elif re.search("part_sg", line):
      part = re.sub(r".*part_sg\t", "", line)
      forms_dict[current_lexeme].append(part)

def string_diff_function(nom, gen, part):
  # temporarily exclude the percent sign
  nom_clean = nom.replace("%", "")
  gen_clean = gen.replace("%", "")
  part_clean = part.replace("%", "")
  diff_start = None
  for i, (a, b, c) in enumerate(zip(nom_clean, gen_clean, part_clean)):
    if not (a == b == c):
      diff_start = i
      break
  if diff_start is None:
    diff_start = min(len(nom_clean), len(gen_clean), len(part_clean))
  nom_diff = nom_clean[diff_start:]
  gen_diff = gen_clean[diff_start:]
  part_diff = part_clean[diff_start:]
  if nom_diff == "":
    nom_diff = "∅"
  if gen_diff == "":
    gen_diff = "∅"
  if part_diff == "":
    part_diff = "∅"
  return f"{nom_diff}/{gen_diff}/{part_diff}"

diff_dict = defaultdict(list)
for key, value in forms_dict.items():
  string_diff = string_diff_function(value[0],value[1],value[2]) # Calls the function to get the string diff; change when we figure out name of function
  diff_dict[string_diff].append(key) # puts the string diff into out new dict with the same key

for i, (key, value) in enumerate(diff_dict.items()):
    print("Class",i, "with pattern", key, "has", len(value), "members, which are:", value, sep =" ")

meta_dict = defaultdict(list)
vowels = 'aeiou'

for sd in diff_dict:
  meta_string_pattern = ''
  # convert to meta pattern
  for char in sd:
    if char == '/':
      meta_string_pattern += '/'
    elif char == '∅':
      meta_string_pattern += '∅'
    elif char in vowels:
      meta_string_pattern += 'V'
    else:
      meta_string_pattern += 'C'
  # use meta pattern as key and add our string difference patter as a val
  meta_dict[meta_string_pattern].append(sd)


# print it all out
for k, v in meta_dict.items():
  print(f'meta-pattern {k} contains string diffs {v}')

  for string_diff in v:
    print(f'{string_diff}: {diff_dict[string_diff]}') # assuming we got string_diff_dict from part 2b