# -*- coding: utf-8 -*-
"""Sinclair_Hansen_Finnish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s2oVySlHXg9DP-SrKK2hSdUHO82wO5Ty
"""

import sys
import torch.nn as nn
import torch
import torch.optim as optim

my_num_of_epochs = 8 #or whatever number you want to choose

if len(sys.argv) > 2 or len(sys.argv) == 1:
    num_epochs = my_num_of_epochs
else:
    num_epochs = int(sys.argv[1]) #This MUST be wrapped in int()


d_emb = 64
d_hid = 64
num_layers = 1
lr=0.0003

train_words = []
train_targets = []
chars = ['#']

with open('finnish_non_violators_train.txt') as f:
    for line in f:
        word = '#' + line.strip() + '#'
        train_words.append(word)
        train_targets.append(0)
        for c in word:
          if c not in chars:
            chars.append(c)

with open('finnish_violators_train.txt') as f:
    for line in f:
        word = '#' + line.strip() + '#'
        train_words.append(word)
        train_targets.append(1)
        for c in word:
          if c not in chars:
            chars.append(c)
chars.sort()
ch2ix = {}

for i, c in enumerate(chars):
  ch2ix[c] = i

train_words_as_indices = []

for word in train_words:
    word_ixs = []
    for c in word:
        word_ixs.append(ch2ix[c])
    train_words_as_indices.append(torch.tensor(word_ixs))



for i in torch.randperm(len(train_words_as_indices)):
  wd = train_words_as_indices[i]
  target = torch.unsqueeze(torch.tensor(train_targets[i]), 0)



class Harmony(nn.Module):
    def __init__(self, vocab_size, d_emb, d_hid, num_classes):
        super().__init__()
        self.embeddings = nn.Embedding(vocab_size, d_emb)
        self.i2R = nn.RNNCell(d_emb, d_hid)
        self.R2o = nn.Linear(d_hid, num_classes)

    def forward(self, ch_indices):
      #ch could mean either character or word,
      #depending on the task
      for j, ch_ix in enumerate(ch_indices):
        emb = self.embeddings(ch_ix)
        emb = torch.unsqueeze(emb, 0)
        if j == 0:
          hidden = self.i2R(emb)
          #defaults to zero hidden vec
        else:
          hidden = self.i2R(emb, hidden)
      return self.R2o(hidden)

net = Harmony(len(chars), d_emb, d_hid, 2)
criterion = nn.CrossEntropyLoss()
optimiser = torch.optim.Adam(net.parameters(), lr=lr)

for epoch in range(num_epochs):
    net.train()
    shuffled_training_ord = torch.randperm(len(train_words_as_indices))
    epoch_loss = 0.0
    num_items = len(train_words_as_indices)
    num_correct = 0

    for i in shuffled_training_ord:
        i = i.item()

        word = train_words_as_indices[i]
        target_v = torch.tensor([train_targets[i]], dtype=torch.long)

        optimiser.zero_grad()

        pred = net(word)
        loss = criterion(pred, target_v)

        epoch_loss += loss.item()

        loss.backward()
        optimiser.step()

        with torch.no_grad():
            argmaxed = torch.argmax(pred, dim=1).item()
            if argmaxed == target_v.item():
                num_correct += 1

    accuracy = num_correct / num_items
    mean_loss = epoch_loss / num_items

    print(f"Epoch {epoch + 1} | Accuracy {accuracy:.4f} | Mean Loss {mean_loss:.6f}")

test_words = []
test_targets = []
chars = ['#']

with open('finnish_non_violators_test.txt') as f:
    for line in f:
        word = '#' + line.strip() + '#'
        test_words.append(word)
        test_targets.append(0)
        for c in word:
          if c not in chars:
            chars.append(c)

with open('finnish_violators_test.txt') as f:
    for line in f:
        word = '#' + line.strip() + '#'
        test_words.append(word)
        test_targets.append(1)
        for c in word:
          if c not in chars:
            chars.append(c)
test_words_as_indices = []
for word in test_words:
    word_ixs = [ch2ix[c] for c in word]
    test_words_as_indices.append(torch.tensor(word_ixs))

print("Now Testing:")
net.eval()
num_correct = 0
num_items = len(test_words_as_indices)
with torch.no_grad():
    for i in range(num_items):
        word = test_words_as_indices[i]
        pred = net(word)
        argmaxed = torch.argmax(pred, dim=1).item()

        if argmaxed == test_targets[i]:
            num_correct += 1
accuracy = 100 * num_correct / num_items
print(f"Test accuracy: {num_correct}/{num_items} = {int(accuracy)}%")
print("Training reached 100% accuracy in 7/10 runs")
print("Testing reached 100% accuracy in 9/10 runs")



