# -*- coding: utf-8 -*-
"""Sinclair_Hansen_Czech_onsets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3M08jnALfQIUxLlQS4KRVWmp2vjGXFP

First, upload the text file to Colab.
"""

list_of_lines = []
with open('Czech_for_onsets.txt', 'r', encoding='utf-8-sig') as f0:
    for line in f0.readlines():
        line = line.rstrip()
        list_of_lines.append(line)

onset_dict = {}
onset_list = []
vowels = 'aeiouʊLR'

for line in list_of_lines:
  for word in line.split():
    onset = ""
    word.lower()
    for letter in word:
      if letter not in vowels:
        onset += letter
      else:
        break
    if onset not in onset_list and onset != "":
      onset_list.append(onset)
    if onset != "" and len(onset) > 1:
      onset_dict[onset] = onset_dict.get(onset, 0) + 1

onset_list = sorted(onset_list)
for word in onset_list:
  print(word)
print("Number of Onsets: " + str(len(onset_list)))

sorted_counts = sorted(onset_dict.items(), key=lambda x: x[1], reverse=True)
counts_list = list(sorted_counts)
print(counts_list)

# Ten onsets that don't occur in English with an example word for each.

print("10 onsets not in English + example")
print("zv: zvi:ʃeni:")
print("hr: hraɲitsi:x ")
print("hl: hlavɲi:x ")
print("zn: zna:silɲeni")
print("zr: zreɪme:ho")
print("mɲ: mɲesti")
print("dv: dvoʊbraŋkovi:")
print("zb: zbitku")
print("zl: zlikvidovali")
print("svj: svjetovi:mi")

"""Some important notes:

Make sure that there are no spaces in your file name. If you end up with a space before .py in your file name, it will cause my shell script to be unable to find your file.
If you develop your script on Colab, do not use "from google.colab import drive". Upload the file in the manner that was demonstrated in class. If your code includes instructions to get a file from Google Drive, it will crash if I run it directly from Python.
Here is a text file of 15,000 Czech words, one word per line, each written in IPA to give a phonemic representation.

Czech_for_onsets.txt Download Czech_for_onsets.txt

Czech has a few consonants that do not occur in English:

ɲ is a palatal nasal a bit like the Spanish n with a  wavy line over it.

x is like the sound at the end of Bach

c  and ɟ are similar to but not exactly like the sounds spelled with ch and  j in English.

There are also versions  of l  and r that act like vowels (like the l and r in English 'pull' and 'purr') which are rewritten in this file as L an R because the IPA characters have little lines underneath each character that don't get picked up in Python.

The objective of this assignment is to find all the onsets that can occur in Czech and then to see how many onset clusters can occur in the language that don't occur in English. The way to do this is to find the longest string of consonants at the beginning of each word that occur before one encounters either a vowel or L or R. Here is one example: on line 8 is the word zru:da. (A colon after a vowel just means that the vowel is long.) This word has onset /zr/ in its initial syllable and this is an onset cluster that never occurs in English.

You will be asked to find not only the set of all onsets in the language (and we are assuming that all the onsets that occur at the beginnings of words are the set of all possible onsets that occur anywhere in a word) but also how many times each onset cluster occurs in the whole dataset.

Suggestions on how to code this:

Part 1:

Import the collections module to initialize a default dictionary for counting how many times each onset cluster occurs in the data.

Initialize an empty list that will contain all the onsets your code finds.

Open the data file and iterate through each line. It may be useful to add the argument
encoding='utf-8-sig'
to the open function. This is explained in Stackoverflow at https://stackoverflow.com/questions/57152985/what-is-the-difference-between-utf-8-and-utf-8-sig.

Find the longest sequence of consonants that occur at the beginning of the word before you encounter one of 'aeiouʊLR'. There are several different ways you can do this. If you know how to do it with a regular expression, that's one way. An alternative is to loop through each character of the word, but break as soon as you encounter one of aeiouʊLR. Add each character that you encounter before breaking to a buffer. If that buffer starts as an empty string, then you can just add each character to it as you go with the + sign, which appends a character to a string. If you make the buffer a list and append to it, then be sure to convert the list to a string at the end with ''join() (no spaces). After breaking out of the loop do two things with the resulting onset string: (1) add it to the list of onsets if it isn't already in the list; (2) increment the value of the key of that onset in the onset count dictionary by one if the onset consists of at least two characters. If the word starts with a vowel, just go on to the next word. Do not include the empty string in your list of onsets.

Once you have the list of onsets, print them out, one per line, in alphabetical order. You can alphabetize a list by wrapping it in sorted(). (3)

Also print out the number of onsets in you onset list. (1)

Next, print out the count of each onset that is a cluster of at least two phonemes. Do this in order, starting with the most frequent. You can do this by again applying sorted() to the values of your onset count dictionary. To order them by the count from largest to smallest, you can give sorted() two additional arguments: (1) key=lambda x: x[1], which sorts on the second item of each tuple (i.e. index 1 as opposed to index 0) in the items and (2) reverse=True, which will start at the highest number. Make sure that you only print out onset clusters, not onsets of length 1. (2)

Part 2: You have to do this part manually and not by further coding since we don't have a list of all the possible onsets in English. Among all the onset clusters in Czech that you found, choose 10 that you think would be the most difficult for an English speaker to pronounce and list them in a print statement. For each one, find one word in the data that begins with that onset and list it with the onset. (2)

Here is what your script should print out:

The onsets that occur in the data at the beginning of words, one per line, in alphabetical order. Do not print it as a list. No repeats. (3)
A count of the number of unique onsets. (1)
The count of how many times each onset cluster occurs as tuples: (onset, count) in descending order. You can just print out like this:
[('pr', 1015), ('st', 329), ('tʃ', 240), ('sp', 206), ('tr', 129), ('kr', 128), ('ts', 124), ('str', 119), ('sk', 110), ... [etc.]

Do not include single-phoneme onsets in this printout. (2)

4. Ten onsets that don't occur in English, with an example word for each. (2)

Do not have your code print out anything more than the above.
"""