# -*- coding: utf-8 -*-
"""Sinclair_Hansen_exercise5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfYGAeVMhgJ2LmgQn1qBxgNGKz9rTnyz

Exercise 5.1
Go to File > New notebook in drive to start a new notebook OR do the folowing on your own .py file,possibly using an IDE such as Visual studio.

(a) Create an empty list that will be later populated with a list of letters.

Create a sentence that has about 100 characters as a string s1 and print it out.

Then create a list l1 out of it by splitting on spaces and print out the list.

Next, create a for loop that iterates through each word in the list. If that word has a least four letters, have a for loop that goes through each letter in the word, lower-cased with lower(), and puts it in the list of letters you initialized at the beginning if that letter has not been seen yet.
Use the keywords "not in" to avoid repeats.

You should end up with the inventory of letters, where each letter occurs just once.

Print out the inventory of letters as a list. Make sure that each letter occurs in the list no more than once.

Then, if on Colab, go to File > Download > Download .py to save your file as a .py file.

Make sure that your name is part of the file name and that there are no spaces in the file name.

Save the file so that you can include it later with subsequent exercises in a .zip archive to submit on Canvas.
"""

l1 = []
s1 = "the quick brown fox jumps over the lazy dog"
print(s1)

for word in s1.split():
  if len(word) > 3:
    for letter in word:
      if letter.lower() not in l1:
        l1.append(letter)

print(l1)