# -*- coding: utf-8 -*-
"""SinclairHansen_Exercise3_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DL4LHG2xcCaqFGTT4RPcYz5PtCLUz_n
"""

# Exercise 3.1

# Go to File > New notebook in drive to start a new notebook OR do the folowing on your own .py file,possibly using an IDE such as Visual studio.

# Create list1 with five items: the numbers from 1 to 5 as integers.

# Create list2 with five items: the numbers from 6 to 10 as integers.

# Append list 2 to list1, which now changes list 1.

# (a) Use nested indices to print out the first item of the inner list which is the last item of list1.

# (b) Insert the item "seven-and-a-half" into the correct place in list 2 so that it makes sense and then print list2.

# (c) Print out the concatenation of list1 with list2. Notice that some numbers will occur more than once.

# Then, if on Colab, go to File > Download > Download .py to save your file as a .py file.

# Make sure that your name is part of the file name and that there are no spaces in the file name.

# Create a .zip file that archives the three .py files from exercises 1, 2 and 3 and submit the .zip file on Canvas.

list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
list1.append(list2)

#a
print(list1[-1][0])

# b
list2.insert(1,"seven-and-a-half")
print(list2)

# (c) Print out the concatenation of list1 with list2. Notice that some numbers will occur more than once.
print(list1 + list2)