# -*- coding: utf-8 -*-
"""Sinclair_Hansen_Exercise6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PpzyKrACwi_4a7hlhLHe5z0ESABd6Yq

Go to File > New notebook in drive to start a new notebook OR do the folowing on your own .py file,possibly using an IDE such as Visual studio.

Write a sentence that has the word 'Mississippi' in it but no other words that have more than ten letters and put it in variable s.
Write a one-line list comprehension that finds all the vowels
in all the words in the sentence that have more than ten letters.
You can use the split() method inside the list comprehension to split the string s in to words.
Print out the list comprehension.

Then, if on Colab, go to File > Download > Download .py to save your file as a .py file.

Make sure that your name is part of the file name and that there are no spaces in the file name.

Create a .zip file that archives the three .py files from exercises 4, 5 and 6 and submit the .zip file on Canvas.
"""

s = "I never know how to spell Mississippi"

l1 = [letter for word in s.split() for letter in word if len(word) > 10 and letter.lower() in 'aeiou']
print(l1)

