# -*- coding: utf-8 -*-
"""SinclairHansen_Exercise2_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArBUjGRd7qR3DUWeUpaD2O97SD3tPrjo
"""

my_list = ['one', 'two', 'three', 'four', 'five']

# (a) The third last item of the list.
print(my_list[-3])

# (b) The items from the second to fourth item inclusive.
print(my_list[1:4])

# (c) The items up to but not including the last item.
print(my_list[:-1])

# (d) The first item.
print(my_list[0])