# -*- coding: utf-8 -*-
"""Sinclair_Hansen_ex_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A42dSSaToRGN5cpR3MqemztrkleI9lX6

Exercise 4.1

Go to File > New notebook in drive to start a new notebook OR do the folowing on your own .py file,possibly using an IDE such as Visual studio.

(a) Create s1 with the string "The quick brown fox (etc.) " that uses all the letters of the alphabet and print it out.

(b) Create l1 from s1 by splittinig s1 on spaces and print out l1.

(c) Create s2 by joining the items on l1 with spaces using join() and print out s2.

(d) Print out the number of characters in s1 including spaces using the len() method.

(e) Print out the number of words in l1 using the len() method.

(f) Print out l1 in reverse. (See notebook 2.)

Then, if on Colab, go to File > Download > Download .py to save your file as a .py file.

Make sure that your name is part of the file name and that there are no spaces in the file name.

Save the file so that you can include it later with subsequent exercises in a .zip archive to submit on Canvas.
"
"""

s1 = "The quick brown fox jumps over the lazy dog"
print(s1)

l1 = s1.split()
print(l1)

s2 = print(' '.join(l1))

print(len(s1))

print(len(l1))

print(l1[::-1])

