# -*- coding: utf-8 -*-
"""SinclairHansen_Exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yp1fpKRpbdA__zigTJWZW3MXm3hLmEf_
"""

print('How\'s it going?')